config/routes.rb
Rails.application.routes.draw do

  root 'pages#welcome'

  get 'portfolio' => 'pages#portfolio'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def welcome
  end

  def portfolio
  end

  def about
  end

  def contact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <link href='https://fonts.googleapis.com/css?family=Roboto:100,300,300italic,500,700' rel='stylesheet' type='text/css'>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="header"> 
  <div class="container"> 
    <div class="row"> 
      <div class="menu col-xs-8"> 
        <ul> 
          <li><%= link_to 'Welcome', root_path %></li>
          <li><%= link_to 'Portfolio', portfolio_path %></li>
          <li><%= link_to 'Blog ', "https://medium.com/@fuzzy" %></li> 
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'Contact', contact_path %></li>
        </ul> 
      </div> 
      <div class="name col-xs-4"> 
        <h1>Fuzzy</h1> 
      </div> 
    </div> 
  </div> 
</div> 

<%= yield %>

<div class="footer">
  <div class="container">
    <ul class="social_media">
      <li><a class="github" href="#">github</a></li>
      <li><a class="linkedin" href="#">linkedin</a></li>
      <li><a class="twitter" href="#">twitter</a></li>
    </ul>
    <p>&copy; 2015 Fuzzy</p>
  </div>
</div>
</body>
</html>

app/views/pages/about.html.erb
<div class="main about">
  <div class="container">
    <div class="row">
      <div class="col-md-6 thumbnail">
        <img alt="Me" src="https://octodex.github.com/images/spidertocat.png" />
      </div>
      <div class="col-md-6">
        <h2>Hello. My name is <span class="highlight">Fuzzy</span></h2>
        <p>Since 2013, I've been pursuing my passion, programming and developing my creativity.</p>
      </div>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="main contact">
  <div class="container">
    <h2>Contact me</h2>
    <div class="row">
      <div class="col-md-2">
        <a class="linkedin" href="#">linkedin</a>
      </div>
      <div class="col-md-2">
        <a class="github" href="#">github</a>
      </div>
      <div class="col-md-2">
        <a class="twitter" href="#">twitter</a>
      </div>
    </div>
  </div>
</div>

app/views/pages/portfolio.html.erb
<div class="main portfolio"> 
  <% if false %>
  <div class="jumbotron slideshow"> 
    <div class="slideshow-container"> 
      <div class="slide"> 
        <img alt="Slide01" src="/assets/slide01-9d5c1b911de14032bbc4cc7b19514447.jpg" /> 
      </div> 
      <div class="slide"> 
        <img alt="Slide02" src="/assets/slide02-3c9662ea3f8d9ce479b5a76aedfa3f7b.jpg" /> 
      </div> 
      <div class="slide"> 
        <img alt="Slide03" src="/assets/slide03-4e85ff59d4201786022aecf410d35d4f.jpg" /> 
      </div> 
      <div class="slide"> 
        <img alt="Slide04" src="/assets/slide04-38bd2e1296452662195acbb9cabafda6.jpg" />
      </div>
      <div class="slide">
        <img alt="Slide05" src="/assets/slide05-0d54918a8bf7af849bbe49da704e6bb6.jpg" />
      </div>
    </div>
  </div>
  <% end %>

  <div class="container">
    <div class="row">
      <a class="col-md-6 project" href="#">
        <div class="thumbnail-header">
          <div class="thumbnail-header-btn"></div>
          <div class="thumbnail-header-btn"></div>
          <div class="thumbnail-header-btn"></div>
        </div>
        <div class="thumbnail">
          <img alt="Project01" src="/assets/project01.jpg" />
        </div>
        <h3>TravelGo’s Booking App</h3>
        <p>NGO liberal change-makers global time of extraordinary change, prevention climate change mobilize shift. Communities, social movement United Nations, Oxfam planned giving Global South humanitarian. Maximize.</p>
      </a>
      <a class="col-md-6 project" href="#">
        <div class="thumbnail-header">
          <div class="thumbnail-header-btn"></div>
          <div class="thumbnail-header-btn"></div>
          <div class="thumbnail-header-btn"></div>
        </div>
        <div class="thumbnail">
          <img alt="Project02" src="/assets/project02.jpg" />
        </div>
        <h3>Breather’s Reservation Site</h3>
        <p>Pursue these aspirations free-speech healthcare sharing economy freedom. Beneficiaries gender rights raise awareness change movements provide. Eradicate, diversification inspire breakthroughs, incubation; solve Peace Corps. Innovate.</p>
      </a>
    </div>

    <div class="row">
      <a class="col-md-6 project" href="#">
        <div class="thumbnail-header">
          <div class="thumbnail-header-btn"></div>
          <div class="thumbnail-header-btn"></div>
          <div class="thumbnail-header-btn"></div>
        </div>
        <div class="thumbnail">
          <img alt="Project03" src="/assets/project03.jpg" />
        </div>
        <h3>EnVogue Events’ Portfolio</h3>
        <p>Informal economies; underprivileged, grantees transformative prosperity. Education best practices connect achieve plumpy'nut. Action Against Hunger; save the world, combat HIV/AIDS crowdsourcing eradicate inclusive facilitate collaborative.</p>
      </a>
      <a class="col-md-6 project" href="#">
        <div class="thumbnail-header">
          <div class="thumbnail-header-btn"></div>
          <div class="thumbnail-header-btn"></div>
          <div class="thumbnail-header-btn"></div>
        </div>
        <div class="thumbnail">
          <img alt="Project04" src="/assets/project04.jpg" />
        </div>
        <h3>Gauntlet Gallery</h3>
        <p>Small-scale farmers; collaborative cities Bill and Melinda Gates best practices equity health theory of social change human experience. Tackle rural development relief worldwide respect, economic.</p>
      </a>
    </div>

    <div class="row">
      <a class="col-md-6 project" href="#">
        <div class="thumbnail-header">
          <div class="thumbnail-header-btn"></div>
          <div class="thumbnail-header-btn"></div>
          <div class="thumbnail-header-btn"></div>
        </div>
        <div class="thumbnail">
          <img alt="Project05" src="/assets/project05.jpg" />
        </div>
        <h3>Koi Pond Online Visitors Guide</h3>
        <p>UNICEF, research Ford Foundation outcomes collaborative consumption turmoil change lives. Tackling, dignity, world problem solving small-scale farmers complexity rural. Emergent humanitarian, necessities effect, challenges of.</p>
      </a>
      <a class="col-md-6 project" href="#">
        <div class="thumbnail-header">
          <div class="thumbnail-header-btn"></div>
          <div class="thumbnail-header-btn"></div>
          <div class="thumbnail-header-btn"></div>
        </div>
        <div class="thumbnail">
          <img alt="Project06" src="/assets/project06.jpg" />
        </div>
        <h3>Academy of Sciences  Newsletter</h3>
        <p>Aid collaborative global network overcome injustice honesty measures. Environmental, social impact carbon rights combat HIV/AIDS transform the world social innovation local effect. Free expression committed.</p>
      </a>
    </div>

  </div>
</div>

app/views/pages/welcome.html.erb
<div class="main home"> 
  <div class="jumbotron"> 
    <div class="container"> 
      <h2>Hello. My name is <span class="highlight">Fuzzy</span> and I have creative ideas and build websites</h2> 
      <a class="btn right" href="portfolio">View my Work</a> 
    </div> 
  </div> 
</div> 